"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useSelectedLayoutSegment } from "next/navigation";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const loginSegment = useSelectedLayoutSegment("modal");
  console.log(`loginSegment = `, loginSegment);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        {modal}
      </body>
    </html>
  );
}
